//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addto
    {
        public long Id_of_order { get; set; }
        public long Id_if_item { get; set; }
        public int Quantity { get; set; }
    
        public virtual Current_order Current_order { get; set; }
        public virtual Item Item { get; set; }
    }
}
